# Generated by Django 5.2.4 on 2026-08-24 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('audience', models.CharField(choices=[('students', 'students'), ('business', 'business'), ('professional', 'professional')], max_length=20)),
                ('platform', models.CharField(choices=[('instagram', 'instagram'), ('ytshorts', 'ytshorts'), ('tiktok', 'tiktok')], max_length=20)),
                ('tone', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adobjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
