# Generated by Django 5.2.4 on 2026-09-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiadgenerator', '0002_alter_adgeneration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgeneration',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
